plugins:
    - jekyll-seo-tag
author: whoisxmlapi
description: >
  Code samples of making requests to whois api services of www.whoisxmlapi.com
logo: https://whoisxmlapi.github.io/assets/img/logo.png
repository: whois-api-llc/whoisxmlapi-samples
show_downloads: true
show_repo_url: true
social:
    name: Whois API, LLC
    links:
        - https://twitter.com/whoisxmlapi
        - https://www.facebook.com/pages/Whois-API-LLC/106782642810963
        - https://www.linkedin.com/in/whois-api-6b257388
        - https://plus.google.com/110739836659192632708
theme: jekyll-theme-cayman
exclude: ["README.md"]
sass:
    sass_dir: assets/_sass
layouts_dir: assets/_layouts
default_repository_url: //github.com/whois-api-llc/
default_releases_url: //github.com/whois-api-llc/